export enum API_TYPE {
    POST = "POST",
    GET = "GET",
    PUT = "PUT",
    DELETE = "DELETE"
}

export enum EVENT_TYPE {
    KAFKA = "KAFKA",
    RABBITMQ = "RABBITMQ"
}

export enum COMMUNICATION_TYPE {
    REST = "REST",
    EVENT = "EVENT"
}

export enum LOGGING_EVENT_TYPE {
    SETUP = "SETUP",
    START = "START",
    END = "END",
    REST_LOOP_IN_PROCESS = "REST_LOOP_IN_PROCESS",
    REST_LOOP_SUCCESSFUL = "REST_LOOP_SUCCESSFUL",
    REST_SUCCESSFUL = "REST_SUCCESSFUL",
    REST_FAILED = "REST_FAILED",
    REST_LOOP_COMPENSATION_START = "REST_LOOP_COMPENSATION_START",
    REST_LOOP_COMPENSATION_IN_PROGRESS = "REST_LOOP_COMPENSATION_IN_PROGRESS"
}